# Generated by Django 4.1.7 on 2023-03-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_app', '0002_rename_personal_info_personal_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_information',
            old_name='DateOfBirth',
            new_name='Date_Of_Birth',
        ),
        migrations.RenameField(
            model_name='personal_information',
            old_name='firstName',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='personal_information',
            old_name='lastName',
            new_name='Last_Name',
        ),
    ]
