# Generated by Django 4.1.7 on 2023-03-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_app', '0003_rename_dateofbirth_personal_information_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Date_Of_Birth', models.DateField()),
                ('Address', models.TextField(blank=True, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='School_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Program', models.CharField(max_length=50)),
                ('Faculty', models.CharField(max_length=50)),
                ('Index_Number', models.CharField(max_length=50)),
                ('GPA', models.CharField(max_length=50)),
                ('Session', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=50)),
                ('Reason', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
