# Generated by Django 4.1.7 on 2023-03-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_app', '0004_guardian_information_school_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_information',
            name='Female',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personal_information',
            name='Male',
            field=models.BooleanField(default=False),
        ),
    ]
