# Generated by Django 4.1.7 on 2023-03-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_app', '0005_personal_information_female_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_information',
            name='Male',
        ),
        migrations.AlterField(
            model_name='personal_information',
            name='Female',
            field=models.BooleanField(default=False, verbose_name='Male'),
        ),
    ]
