# Generated by Django 4.1.7 on 2023-03-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_app', '0007_personal_information_male_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_information',
            name='Female',
        ),
        migrations.RemoveField(
            model_name='personal_information',
            name='Male',
        ),
        migrations.AddField(
            model_name='personal_information',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=100, null=True),
        ),
    ]
