# Generated by Django 4.1.7 on 2023-03-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_app', '0009_remove_guardian_information_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian_information',
            name='Guardian',
        ),
        migrations.RemoveField(
            model_name='personal_information',
            name='Gender',
        ),
        migrations.AddField(
            model_name='guardian_information',
            name='Occupation',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school_information',
            name='Level',
            field=models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guardian_information',
            name='Address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
